name: Cron Task

on:
  workflow_dispatch:
  schedule:
    - cron: "16 4 * * *"

jobs:
  build:
    name: Checkin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Get dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Checkin
        run: |
          python 1p3a.py
        env:
          DEVICE_ID: ${{ secrets.DEVICE_ID }}
          AUTH: ${{ secrets.AUTH }}
          ALERT_URL: ${{ secrets.ALERT_URL }}
          RUN_ON_CI: 1
